name: API docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          cd api
          perl asmdoc.pl -author -version ../basic/basic.inc ../basic/modules/*.asm

      - uses: actions/checkout@v2
          with:
            ref: gh-pages

      - name:
        docs: |
          echo date > generated.txt
          echo git config user.name github-actions
          echo git config user.email github-actions@github.com
          echo git add .
          echo git commit -m "generated"
          echo git push
