name: API docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          cd api
          perl asmdoc.pl -author -version ../basic/basic.inc ../basic/modules/*.asm
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout gh-pages
          echo git add .
          echo git commit -m "generated"
          echo git push
