name: API docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  asmdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        run: |
          git fetch
          git checkout main
          git pull
          cd api
          perl asmdoc.pl -author -version ../basic/basic.inc ../basic/modules/*.asm
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          echo git add .
          echo git commit -m "asmdoc"
          echo git push
