name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get RASM
        run: |
          sudo apt-get update
          sudo apt-get install git
